Force coveralls 0.8
running bundle update in ui-classic, I'm seeing `Using coveralls 0.7.1 (was 0.8.23)`.

That seems to lead to a coveralls failure on (non-failing) travis:

Coveralls encountered an exception:
NoMethodError
undefined method `coverage' for #<SimpleCov::SourceFile:0x000000004bd2fb40>
manageiq-ui-classic/vendor/bundle/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:50:in `block in format'
ruby-2.5.7/lib/ruby/2.5.0/forwardable.rb:229:in `each'
ruby-2.5.7/lib/ruby/2.5.0/forwardable.rb:229:in `each'
coveralls-0.7.1/lib/coveralls/simplecov.rb:40:in `format'
simplecov-0.18.1/lib/simplecov/result.rb:49:in `format!'
simplecov-0.18.1/lib/simplecov/configuration.rb:196:in `block in at_exit'
simplecov-0.18.1/lib/simplecov.rb:201:in `run_exit_tasks!'
simplecov-0.18.1/lib/simplecov/defaults.rb:31:in `block in <top (required)>'

Forcing 0.8